KSSB_INSTRUMENT := N
KCSAN_SANITIZE := n
KASAN_SANITIZE := n
KCOV_INSTRUMENT := n
UBSAN_SANITIZE := n

obj-$(CONFIG_KSSB) += kssb.o kssb_pso.o kssb_context.o kssb_llist.o
obj-$(CONFIG_KSSB) += tests/
